@echo off
echo Creating a new virtual environment...
python -m venv venv
echo Activating the virtual environment...
call .\venv\Scripts\activate
echo Installing the requirements...
pip install -r requirements.txt
